<?php
//
use Drupal\node\Entity\Node;

function jobs_theme()
{

  $theme['node__job'] = array(
    'template' => 'node--job',
    'base hook' => 'node',
  );

  $theme['offers-view'] = array(
    'variables' => ['offers' => NULL],
  );

  $theme['applies'] = array(
    'variables' => ['applies' => NULL],
  );

  $theme['offer-show'] = array(
    'variables' => ['offer' => NULL, 'form' => NULL],
  );

  return $theme;
}
